travis:
  secure:
    BINSTAR_TOKEN: adUSddiLANrtooIGUSGJIdxkx9n5gEuR/c5PdqklQ5yJySZe6rhyZDk8XeXbC5bMnvrWWjvOBEBGNdwx77dP1t+4DvmCBOXQ8pqj+WUrFLcr8TUU8ZyOewXfY232893XE2Rug3mHaMPxRPWdaGpWsNaHtqhpMBcCcfB1S1zLkFgTotGbdWLVAS8O6eWHS1jmoyp67QTxMJUkUXO/sZBGpYY+XTE2K5uin7cUK8XPuzW6rIs3V2ZeyrooqmB6dnuDgaNcKoihALb4TfYfOx0IQW7jqbViZkZQGHBN4FhMEiXLSX3Cu6vHhbSFnOyMUWA/NFDMQGRyUqxy2i/i5feQudpX5/iMAtgAA0UgIfos/bfDRFmhORkjh1+4Z+yYXrxB+r/VQ22Rjz88UKpOqX2I+qu1W22O/8fMSFIXrVRZLpKbkhbY9+8tYwnQD+GTFfgwXrErsU1sgm8x3fexwm71xejBdoyG+4ZzySVoVVYRpuoM/oH0WXl3brzt+cDo4Mtcf7rNdRrINn3IIpDou4i+su3l4sTiKcjxA07XWq3sJP75ZU2kECFtjZIeIDDufxRsK/2vODu1ZZWOQu1Ei6eRxtGht+tfOnxoX0Rgo1sykEf/hCDwp7f8P++DYiwQzye3OHroofVT8yOJ6kWO5g6EKuMe0uycI0yCz5XJ5ChVSEQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
